apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  selector:
    app: checkout
  ports:
    - protocol: TCP
      port: 9090  # Port the service is exposed on within the cluster
      targetPort: 9090  # Container port to send traffic to
  type: ClusterIP  # Default type, only accessible within the cluster
