apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: checkout-service
build:
  artifacts:
    - image: gcr.io/wipro-425519/checkout-service
      context: ./checkout-service
      docker:
        dockerfile: ./checkout-service/Dockerfile
  tagPolicy:
    gitCommit: {}
  platforms: "linux/amd64"
deploy:
  kubeContext: gke_wipro-425519_us-central1_automation-cluster
  kubectl: {}
manifests:
      kustomize:
        paths:
          - k8s/overlays/dev
portForward:
  - resourceType: service
    resourceName: checkout-service
    namespace: default
    port: 9090
    localPort: 9091
