apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: checkout-service
build:
  artifacts:
    - image: gcr.io/${GCP_PROJECT_ID}/checkout-service
      context: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
deploy:
  kubeContext: gke_wipro-425519_us-central1_automation-cluster
  kubectl: {}
manifests:
      kustomize:
        paths:
          - k8s/overlays/dev
portForward:
  - resourceType: service
    resourceName: checkout-service
    namespace: default
    port: 9090
    localPort: 9091
