apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: checkout-service
build:
  artifacts:
    - image: gcr.io/${GCP_PROJECT_ID}/checkout-service
      context: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  default-repo: gcr.io/${GCP_PROJECT_ID}
deploy:
  kubeContext: gke_wipro-425519_us-central1_automation-cluster
  kubectl:
    manifests:
      - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: checkout-service
    namespace: default
    port: 9090
    localPort: 9091
