name: Deploy to GCP with Skaffold

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: ${{ steps.auth.outputs.access_token }}
          workload_identity_provider: 'projects/wipro-425519/locations/global/workloadIdentityPools/wipro-425519.svc.id.goog'
          service_account: automation-gsa@wipro-425519.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info

#      - name: Set up Google Cloud SDK
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

#      - name: Run Skaffold Deploy
#        run: skaffold run -f ../checkout-service/skaffold.yaml
#        env:
#          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.18.8'

