name: Deploy to GCP with Skaffold

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/683387273161/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: automation-gsa@wipro-425519.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Run Skaffold Deploy
        run: skaffold run -f ./checkout-service/skaffold.yaml
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}


